- ccloud/migrate-schemas-to-confluent-cloud/docker-compose-executable-onprem-to-cloud.yml
- ccloud/replicator/docker-compose-connect-onprem-to-cloud.yml
- ccloud/replicator/docker-compose-executable-onprem-to-cloud-topicrecordnamestrategy.yml
- ccloud/replicator/docker-compose-executable-onprem-to-cloud.yml
- environment/mdc-plaintext/docker-compose.yml
- environment/plaintext/docker-compose.yml
without the new setting, brokers complain about insufficient broker count
> added KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR for 6.0.0

- connect/connect-cdc-oracle12-source/.gitignore
- connect/connect-cdc-oracle12-source/cdc-oracle12-cdb-table.sh
- connect/connect-cdc-oracle12-source/cdc-oracle12-pdb-table.sh
- connect/connect-cdc-oracle12-source/docker-compose.plaintext-cdb-table.yml
- connect/connect-cdc-oracle12-source/docker-compose.plaintext-pdb-table.yml
Update Oracle CDC Source script for confluentinc-kafka-connect-oracle-cdc-0.1.2-rc-3d761ad-preview
> Update Oracle CDC Source script for confluentinc-kafka-connect-oracle-cdc-0.1.2-rc-3d761ad-preview

- connect/connect-cdc-oracle12-source/README.md
- connect/connect-cdc-oracle12-source/cdc-oracle12-cdb-table.sh
- connect/connect-cdc-oracle12-source/cdc-oracle12-pdb-table.sh
- connect/connect-cdc-oracle12-source/docker-compose.plaintext-cdb-table.yml
- connect/connect-cdc-oracle12-source/docker-compose.plaintext-pdb-table.yml
Updated oracle-cdc script with the latest snapshot
> Updated oracle-cdc script with the latest snapshot

- connect/connect-cdc-oracle12-source/cdc-oracle12-cdb-table.sh
- connect/connect-cdc-oracle12-source/cdc-oracle12-pdb-table.sh
- connect/connect-cdc-oracle12-source/docker-compose.plaintext-cdb-table.yml
- connect/connect-cdc-oracle12-source/docker-compose.plaintext-pdb-table.yml
Rollback to the previous version since I found a bug with the latest version. https://confluent.slack.com/archives/C0112BNAQBX/p1607429534249300?thread_ts=1607387339.248700&cid=C0112BNAQBX
> Rollback to the previous version

- connect/connect-cdc-oracle12-source/cdc-oracle12-cdb-table.sh
- connect/connect-cdc-oracle12-source/cdc-oracle12-pdb-table.sh
Add a step to create a redo-log-topic before a connector is created
More context can be found here: https://confluentinc.atlassian.net/browse/CC-13104
> Add a step to create a redo-log-topic before a connector is created

- environment/plaintext/docker-compose.yml
Added dependencies for ksqldb-server and ksqldb-cli
> Added dependencies for ksqldb-server and ksqldb-cli

- connect/connect-cdc-oracle12-source/README.md
- connect/connect-cdc-oracle12-source/cdc-oracle12-cdb-table.sh
- connect/connect-cdc-oracle12-source/cdc-oracle12-pdb-table.sh
- connect/connect-cdc-oracle12-source/docker-compose.plaintext-cdb-table.yml
Update the connector version to confluentinc-kafka-connect-oracle-cdc-1.0.0-rc-70b3f21-preview
> Update the connector version to confluentinc-kafka-connect-oracle-cdc-1.0.0-rc-70b3f21-preview

- connect/connect-cdc-oracle12-source/README.md
- connect/connect-cdc-oracle12-source/cdc-oracle12-cdb-table.sh
- connect/connect-cdc-oracle12-source/cdc-oracle12-pdb-table.sh
- connect/connect-cdc-oracle12-source/docker-compose.plaintext-cdb-table.yml
- connect/connect-cdc-oracle12-source/docker-compose.plaintext-pdb-table.yml
Update the scripts with the latest version of Oracle CDC Source (confluentinc-kafka-connect-oracle-cdc-1.0.0-rc-56069d9-preview)
> Update the scripts with the latest version of Oracle CDC Source

- operator/replicator-tls-only/start.sh
I've added the following to replicator payload in the connector section, I think it makes sense: 
```
"topic.rename.format": "${topic}_replica",
```
> Added topic rename to operator replicator payload

- operator/early-access/confluent-platform.yaml
Without the internalTopicReplicatorFactor for C3 and Connect we fail to start the CRD
> Adding internalTopicReplicatorFactor

- operator/replicator-tls-only/start.sh
> Operator: replicator tls: consumer typo

- connect/connect-mongodb-sink/Dockerfile.mongo-sink-repro-sharding
- connect/connect-mongodb-sink/docker-compose.plaintext-mongo-sink-repro-sharding.yml
- connect/connect-mongodb-sink/mongo-sink-repro-sharding.sh
Example of what happen when Kafka Connector Mongo Sink tries to upsert in a sharded collection (spoiler it fails with the error message: `Failed to target upsert by query :: could not extract exact shard key`) and how to fix it by providing a way to find the shard (business key).
> Basic Mongodb sharding example

- ccloud/connect-local-mqtt-source/README.md
- ccloud/connect-local-mqtt-source/basic_data.json
- ccloud/connect-local-mqtt-source/basic_schema.json
- ccloud/connect-local-mqtt-source/docker-compose.yml
- ccloud/connect-local-mqtt-source/mosquitto.conf
- ccloud/connect-local-mqtt-source/mqtt.sh
- ccloud/connect-local-mqtt-source/password
- ccloud/connect-local-mqtt-source/stop.sh
I needed an example of running the MQTT source yourself with CC as the Kafka backend.
> Added example of MQTT source in Connect Worker connected to CC

- ksqldb/udf-logging/README.md
- ksqldb/udf-logging/docker-compose.plaintext.yml
- ksqldb/udf-logging/log4j.template.properties
- ksqldb/udf-logging/start.sh
- ksqldb/udf-logging/stop.sh
- ksqldb/udf-logging/udf-custom-logger/pom.xml
- ksqldb/udf-logging/udf-custom-logger/src/main/java/com/example/FormulaUdfCustomLogger.java
- ksqldb/udf-logging/udf-custom-logger/src/main/resources/logback.xml
- ksqldb/udf-logging/udf-simple-logging/pom.xml
- ksqldb/udf-logging/udf-simple-logging/src/main/java/com/example/FormulaUdfLog4jCustomLoggingLevel.java
- ksqldb/udf-logging/udf-simple-logging/src/main/java/com/example/FormulaUdfSimpleLog4jLogging.java
This PR showcases how to use a logger with ksqlDB UDF.
It explains how to use the default logging config, how to update the log level, and how to set up a UDF project to leverages a different logging framework than the one used by ksqlDB (using classpath isolation).
> Sample UDF logging

- replicator/connect/connect-plaintext-repro-deleted-source-topic.sh
Update the existing reproducer with the replicator status
> WIP: Update reproducer when source topic is deleted while being replicated

- docs/how-to-use.md
- environment/plaintext/docker-compose.yml
- environment/plaintext/start.sh
Adding ability for plaintext to enable multi node deployment. This is the initial PR.
> Additional plaintext brokers via profile/environment variable

- connect/connect-jms-sag-um-sink/README.md
- connect/connect-jms-sag-um-sink/docker-compose.plaintext.yml
- connect/connect-jms-sag-um-sink/jms-sag-um-sink.sh
- connect/connect-jms-sag-um-sink/stop.sh
- connect/connect-jms-sag-um-source/README.md
- connect/connect-jms-sag-um-source/docker-compose.plaintext.yml
- connect/connect-jms-sag-um-source/jms-sag-um-source.sh
- connect/connect-jms-sag-um-source/stop.sh
JMS Source and Sink Connector examples  with [Software AG Universal Messaging](https://documentation.softwareag.com/onlinehelp/Rohan/num10-3/10-3_UM_webhelp/index.html).
These examples use the [softwareag/universalmessaging-server](https://hub.docker.com/r/softwareag/universalmessaging-server) images and it comes with 90 days of free trial for non-production use.
> SAG Universal Messaging JMS Source and Sink Connector examples 

- multi-data-center/cluster-linking/automatic-topic-creation-filters.json
- multi-data-center/cluster-linking/start-plaintex-automatic-topic-creation.sh
Extend the current Cluster Linking demo with a sample of automatic topic creation configuration
> Sample Cluster linking automatic topic creation

- environment/plaintext/docker-compose.yml
- environment/plaintext/start.sh
Enabling Kafka docker playground to use the following:
https://docs.confluent.io/platform/current/schema-registry/develop/maven-plugin.html#schema-registry-derive-schema
The GitHub code base where the web server is hosted is in this github repo:
https://github.com/cdpop/sr-plugin-container
> Version 1.0 of sr_plugins

- other/rbac-with-anonymous-sr/README.md
- other/rbac-with-anonymous-sr/docker-compose.rbac-sasl-plain.yml
- other/rbac-with-anonymous-sr/scripts/create-role-bindings-anonymous.sh
- other/rbac-with-anonymous-sr/start.sh
- other/rbac-with-anonymous-sr/stop.sh
Hi Vincent,
here is the first of two PR from my tests as discussed on Slack. This provides an example for anonymous SR access in a simple RBAC setup. Basically 2 overrides and an additional script to create the role bindings for ANONYMOUS principal.
Kind regards,
Roman
> Added anonymous SR-example with RBAC

- other/recover-from-schema-hard-deletion/README.md
- other/recover-from-schema-hard-deletion/__files/schemas/ids/1
- other/recover-from-schema-hard-deletion/custom-schemaregistryclient-using-local-schemas/.idea/codeStyles/Project.xml
- other/recover-from-schema-hard-deletion/custom-schemaregistryclient-using-local-schemas/.idea/codeStyles/codeStyleConfig.xml
- other/recover-from-schema-hard-deletion/custom-schemaregistryclient-using-local-schemas/.idea/compiler.xml
- other/recover-from-schema-hard-deletion/custom-schemaregistryclient-using-local-schemas/.idea/encodings.xml
- other/recover-from-schema-hard-deletion/custom-schemaregistryclient-using-local-schemas/.idea/jarRepositories.xml
- other/recover-from-schema-hard-deletion/custom-schemaregistryclient-using-local-schemas/.idea/misc.xml
- other/recover-from-schema-hard-deletion/custom-schemaregistryclient-using-local-schemas/.idea/vcs.xml
- other/recover-from-schema-hard-deletion/custom-schemaregistryclient-using-local-schemas/.idea/workspace.xml
- other/recover-from-schema-hard-deletion/custom-schemaregistryclient-using-local-schemas/pom.xml
- other/recover-from-schema-hard-deletion/custom-schemaregistryclient-using-local-schemas/src/test/java/CustomSchemaRegistryClientUsingLocalSchemasTest.java
- other/recover-from-schema-hard-deletion/custom-schemaregistryclient-using-local-schemas/src/test/resources/logback.xml
- other/recover-from-schema-hard-deletion/docker-compose.plaintext.yml
- other/recover-from-schema-hard-deletion/start.sh
- other/recover-from-schema-hard-deletion/stop.sh
When data has been serialized but the associated schema is not available, the data can not be deserialized anymore.
This PR aims at proposing techniques to mitigate a situation where a single schema has been hard deleted or a total loss of a Schema Registry.
> Exploring techniques to recover schemas deleted from SR

- tools/datadog/datadog/conf.d/cp.yml
- tools/datadog/docker-compose.plaintext.yml
Added config to enable ksqldb monitoring in datadog.  Also added datagen connector to allow testing of ksqldb streams.
> Ksqldb datadog logging

- ccloud/fully-managed-connect-cdc-oracle19-source/README.md
README incorrectly referenced the IBM MQ connector script
> Update README.md to reference correct script

- ksqldb/materialized-view/README.md
Fix url in ksqldb/materialized-view readme
> Fix typo in ksqldb readme

- ksqldb/quickstart-example/README.md
- ksqldb/quickstart-example/start.sh
- ksqldb/quickstart-example/stop.sh
Adding the first ksqlDB example with the Quickstart example
> ksqlDb - Add Quickstart

- ksqldb/schema-evolution/README.md
- ksqldb/schema-evolution/start.sh
- ksqldb/schema-evolution/stop.sh
- ksqldb/simple-example-vanilla-producer/README.md
- ksqldb/simple-example-vanilla-producer/start.sh
- ksqldb/simple-example-vanilla-producer/stop.sh
Add Vanilla example + Schema Evolution example
> ksqldb - add schema evolution and quickstart repro

- ksqldb/foreign-key-table-table-join/README.md
- ksqldb/foreign-key-table-table-join/start.sh
- ksqldb/foreign-key-table-table-join/stop.sh
- ksqldb/stream-stream-join/README.md
- ksqldb/stream-stream-join/start.sh
- ksqldb/stream-stream-join/stop.sh
- ksqldb/stream-table-join-timestamp-based-join-failure/README.md
- ksqldb/stream-table-join-timestamp-based-join-failure/start.sh
- ksqldb/stream-table-join-timestamp-based-join-failure/stop.sh
- ksqldb/stream-table-join/README.md
- ksqldb/stream-table-join/start.sh
- ksqldb/stream-table-join/stop.sh
- ksqldb/table-table-join/README.md
- ksqldb/table-table-join/start.sh
- ksqldb/table-table-join/stop.sh
Add 3 new reproduction models:
- TABLE - TABLE JOIN
- STREAM - TABLE JOIN
- STREAM - TABLE JOIN issue to show timestamp based join failure
- Foreign Key TABLE - TABLE join
> ksqldb - add JOIN examples

- docs/content-template.md
- ksqldb/aggregate-last-events-by-customer/README.md
- ksqldb/aggregate-last-events-by-customer/start.sh
- ksqldb/aggregate-last-events-by-customer/stop.sh
- ksqldb/handle-null-value-coalesce/README.md
- ksqldb/handle-null-value-coalesce/start.sh
- ksqldb/handle-null-value-coalesce/stop.sh
- ksqldb/hopping-windows/README.md
- ksqldb/hopping-windows/start.sh
- ksqldb/hopping-windows/stop.sh
- ksqldb/manage-deserialization-errors/start.sh
- ksqldb/multi-join/README.md
- ksqldb/multi-join/start.sh
- ksqldb/multi-join/stop.sh
- ksqldb/nested-json/README.md
- ksqldb/nested-json/start.sh
- ksqldb/nested-json/stop.sh
- ksqldb/rekey-stream-with-value/README.md
- ksqldb/rekey-stream-with-value/start.sh
- ksqldb/rekey-stream-with-value/stop.sh
- ksqldb/session-windows/README.md
- ksqldb/session-windows/start.sh
- ksqldb/session-windows/stop.sh
- ksqldb/tombstone-propagated-table/README.md
- ksqldb/tombstone-propagated-table/start.sh
- ksqldb/tombstone-propagated-table/stop.sh
- ksqldb/tumbling-windows/README.md
- ksqldb/tumbling-windows/start.sh
- ksqldb/tumbling-windows/stop.sh
- Add Multi JOIN
- Add Windows examples (hopping, session, tumbling)
- Update the docs
- Add "Why tombstone is not propagated to table derived from CTAS in ksqlDB"
- Add a Nested JSON example
- Add How to aggregate the last X events by an ID
> ksqldb - Add Multi join

- docs/content-template.md
- ksqldb/handle-empty-array-explode/README.md
- ksqldb/handle-empty-array-explode/start.sh
- ksqldb/handle-empty-array-explode/stop.sh
- Add How to handle empty array or null value within EXPLODE function using CASE
-
> KSQL - Add more examples

- ksqldb/composite-pkey-materialized-table/README.md
- ksqldb/composite-pkey-materialized-table/start.sh
- ksqldb/composite-pkey-materialized-table/stop.sh
Select from Materialized table by composite pkey=struct(one attribute is null)
> ksqldb - Select from Materialized table by composite pkey=struct

- docs/content-template.md
- schema-registry/kafka-avro-console-producer-union/README.md
- schema-registry/kafka-avro-console-producer-union/start.sh
- schema-registry/kafka-avro-console-producer-union/stop.sh
- schema-registry/multiple-event-type-same-topic-api/README.md
- schema-registry/multiple-event-type-same-topic-api/start.sh
- schema-registry/multiple-event-type-same-topic-api/stop.sh
- schema-registry/use-diffrent-key-value-serializer-console-producer/README.md
- schema-registry/use-diffrent-key-value-serializer-console-producer/start.sh
- schema-registry/use-diffrent-key-value-serializer-console-producer/stop.sh
- [How to produce Avro records via kafka-avro-console-producer with Union](https://github.com/vdesabou/kafka-docker-playground/tree/master/schema-registry/kafka-avro-console-producer-union) ![not tested](https://img.shields.io/badge/CI-not%20tested!-violet)
- [Multiple event types in the same topic via Schema Registry API](https://github.com/vdesabou/kafka-docker-playground/tree/master/schema-registry/multiple-event-type-same-topic-api) ![not tested](https://img.shields.io/badge/CI-not%20tested!-violet)
- [How to use different Key and Value serializer with kafka-avro-console-producer](https://github.com/vdesabou/kafka-docker-playground/tree/master/schema-registry/use-diffrent-key-value-serializer-console-producer) ![not tested](https://img.shields.io/badge/CI-not%20tested!-violet)
> Schema registry - Add new examples for Schema Registry

- ksqldb/tumbling-windows/start.sh
Add an example with out-of-order events with the tumbling window
> ksqldb - add out-of-order example with tumbling window

- environment/plaintext/docker-compose.yml
- environment/plaintext/start.sh
- schema-registry/data-contracts/README.md
- schema-registry/data-contracts/data/order.avsc
- schema-registry/data-contracts/data/order_metadata.json
- schema-registry/data-contracts/data/order_ruleset.json
- schema-registry/data-contracts/docker-compose.plaintext.yml
- schema-registry/data-contracts/start.sh
- schema-registry/data-contracts/stop.sh
- scripts/cli/playground
- scripts/cli/src/lib/utils_function.sh
Also add Kafka REST Proxy component
> Schema Registry - Add example for Data Contracts

- docs/content-template.md
Update doc to add the Data Contracts example
> Schema Registry - Update doc

- operator/capturing-authentication-log-details/README.md
- operator/capturing-authentication-log-details/confluent-platform-sasl-plain.yaml
- operator/capturing-authentication-log-details/start.sh
- operator/capturing-authentication-log-details/stop.sh
This PR is a variant of #4630 but with CFK.
The main differences is the way of overriding the logger
> Capturing Authentication Log details with CFK

- connect/connect-jdbc-aws-redshift-source/README.md
fix jq command
fix driver setting
> fix typo in Redshift Source Connector

- .gitignore
- academy/connect-connect-debezium-sqlserver-source/debezium-sqlserver-source-repro-pipeline-example.sh
- ccloud/fm-debezium-sqlserver-legacy-source/fully-managed-debezium-legacy-sqlserver-source-ssl.sh
- ccloud/fm-debezium-sqlserver-legacy-source/fully-managed-debezium-legacy-sqlserver-source.sh
- ccloud/fm-debezium-sqlserver-v2-source/fully-managed-debezium-v2-sqlserver-source-ssl.sh
- ccloud/fm-debezium-sqlserver-v2-source/fully-managed-debezium-v2-sqlserver-source.sh
- ccloud/fm-jdbc-sqlserver-sink/fully-managed-sqlserver-microsoft-sink.sh
- ccloud/fm-jdbc-sqlserver-source/fully-managed-sqlserver-source.sh
- connect/connect-debezium-sqlserver-source/README.md
- connect/connect-debezium-sqlserver-source/debezium-sqlserver-source-incremental-snapshot.sh
- connect/connect-debezium-sqlserver-source/debezium-sqlserver-source-ssl.sh
- connect/connect-debezium-sqlserver-source/debezium-sqlserver-source-standalone-worker.sh
- connect/connect-debezium-sqlserver-source/debezium-sqlserver-source.sh
- connect/connect-jdbc-sap-hana-sink/docker-compose.plaintext.yml
- connect/connect-jdbc-sap-hana-source/docker-compose.plaintext.yml
- connect/connect-jdbc-sqlserver-sink/README.md
- connect/connect-jdbc-sqlserver-sink/sqlserver-jtds-sink-ssl.sh
- connect/connect-jdbc-sqlserver-sink/sqlserver-jtds-sink.sh
- connect/connect-jdbc-sqlserver-sink/sqlserver-microsoft-sink-ssl.sh
- connect/connect-jdbc-sqlserver-sink/sqlserver-microsoft-sink.sh
- connect/connect-jdbc-sqlserver-source/README.md
- connect/connect-jdbc-sqlserver-source/sqlserver-jtds-ssl.sh
- connect/connect-jdbc-sqlserver-source/sqlserver-jtds.sh
- connect/connect-jdbc-sqlserver-source/sqlserver-microsoft-ssl.sh
- connect/connect-jdbc-sqlserver-source/sqlserver-microsoft.sh
- connect/connect-sap-hana-sink/docker-compose.plaintext.yml
* reproduction-models
* fix self certs
* 2.00.076.00.20240701.1
> Features3 (#4)

- .github/workflows/ci.yml
- ccloud/fm-gcp-bigtable-sink/fully-managed-gcp-bigtable-sink.sh
- connect/connect-gcp-bigtable-sink/gcp-bigtable-sink-proxy.sh
- connect/connect-gcp-bigtable-sink/gcp-bigtable-sink.sh
- docs/content-template.md
- other/kafka-connect-jsonata/README.md
- other/kafka-connect-jsonata/docker-compose.plaintext.yml
- other/kafka-connect-jsonata/jsonata-drop-tombstone.sh
- scripts/cli/src/lib/utils_function.sh
* Add example for jsonata #5756
* check does not work with CI for some reasons, only relying on lag
* Issue with adding tcpdump #5917
> 16092024 2 (#9)

- connect/connect-filestream-sink/filestream-sink.sh
- connect/connect-http-sink/http_no_auth.sh
- connect/connect-http-sink/http_oauth2_auth.sh
- scripts/cli/completions.bash
- scripts/cli/playground
- scripts/cli/playground.json
- scripts/cli/playground.yaml
- scripts/cli/predefined-schemas/json/users.json
- scripts/cli/snippets/sink.sh
- scripts/cli/src/bashly.yml
- scripts/cli/src/commands/connector/create-or-update.sh
- scripts/cli/src/create-connector-post-template-initial-state.json
* Add --initial-state option to "playground connector create-or-update" #5929
* faker location
> 26092024 2 (#13)

- environment/plaintext/docker-compose.yml
- environment/plaintext/grafana/provisioning/dashboards/flink.json
- environment/plaintext/prometheus/prometheus.yml
- flink/flink_app_mode/docker-compose.yml
- flink/flink_app_mode/start.sh
- flink/flink_app_mode/stop.sh
- flink/flink_session_mode/docker-compose.yml
- flink/flink_session_mode/start.sh
- flink/flink_session_mode/stop.sh
- flink/flink_session_sql_mode/docker-compose.yml
- flink/flink_session_sql_mode/start.sh
- flink/flink_session_sql_mode/stop.sh
- scripts/flink_download_connectors.sh
- scripts/utils.sh
PR working on adding grafana dashboards where I am further testing to make sure dashboard gets populated properly and env variables work as expected
> working on adding grafana dashboards for flink

- connect/connect-spool-dir-source/docker-compose.plaintext.yml
Use https://www.confluent.io/hub/confluentinc/kafka-connect-spooldir for testing spooldir connector
> use confluentinc/kafka-connect-spooldir
